package group14.foodfetch;

import android.graphics.Bitmap;

/**
 * Created by s141680 on 8-3-2017.
 * by Manning Zhang
 */
public class Announcement {

    //constructors:---------------------------------------------------------------------------------
    public Announcement(String title, String foodType){
        setTitle(title);
        setFoodType(foodType);
        setAnnouncementID(1);  ///should be removed by a generator function later
    }
    //----------------------------------------------------------------------------------------------

    //Variables contained in each post==============================================================
    //Variables have to be filled by users:
    private String title;   //compulsory
    private String foodType;  //compulsory
    private String description;   //optional
    private Bitmap foodPic;  //optional

    //variables will be automatically generated:
    private String author;
    private String publishDate; //will be generated by the system when publish button is clicked
    private int announcementID;
    //private boolean display; display is commented since it is the reverse of acceptence.
    //==============================================================================================


    //All set&get functions for private variables===================================================
    //set functions:
    public void setTitle(String title) {
        this.title = title;
    }

    public void setFoodType(String foodType) {
        this.foodType = foodType;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate;
    }

    public void setAnnouncementID(int announcementID) {
        this.announcementID = announcementID;
    }

    public void setFoodPic(Bitmap foodPic) {
        this.foodPic = foodPic;
    }



    //get functions:
    public String getTitle() {
        return title;
    }

    public String getFoodType() {
        return foodType;
    }

    public String getDescription() {
        return description;
    }

    public String getAuthor() {
        return author;
    }

    public String getPublishDate() {
        return publishDate;
    }

    public int getAnnouncementID() {
        return announcementID;
    }

    public Bitmap getFoodPic() {
        return foodPic;
    }



    //==============================================================================================


}
