package group14.foodfetch;

import android.graphics.Bitmap;

/**
 * Created by s141680 on 27-3-2017.
 */

abstract class Publish {
    //Variables contained in each post==============================================================
    //Variables have to be filled by users:
    private String title;   //compulsory
    private String foodType;  //compulsory
    private String expiredDate;   //compulsory
    private Bitmap foodPic;  //optional
    private String description;   //optional

    //variables will be automatically generated:
    private String author;
    private String publishDate; //will be generated by the system when publish button is clicked
    private int publishID;
    private boolean acceptence;
    //private boolean display; display is commented since it is the reverse of acceptence.
    //==============================================================================================


    //All set&get functions for private variables===================================================
    //set functions:
    protected void setTitle(String title) {
        this.title = title;
    }

    protected void setFoodType(String foodType) {
        this.foodType = foodType;
    }

    protected void setExpiredDate(String expiredDate) {
        this.expiredDate = expiredDate;
    }

    protected void setFoodPic(Bitmap foodPic) {
        this.foodPic = foodPic;
    }

    protected void setDescription(String description) {
        this.description = description;
    }

    protected void setAuthor(String author) {
        this.author = author;
    }

    protected void setPublishDate(String publishDate) {
        this.publishDate = publishDate;
    }

    protected void setPublishID(int publishID) {
        this.publishID = publishID;
    }

    protected void setAcceptence(boolean acceptence) {
        this.acceptence = acceptence;
    }


    //get functions:
    protected String getTitle() {
        return title;
    }

    protected String getFoodType() {
        return foodType;
    }

    protected String getExpiredDate() {
        return expiredDate;
    }

    protected Bitmap getFoodPic() {
        return foodPic;
    }

    protected String getDescription() {
        return description;
    }

    protected String getAuthor() {
        return author;
    }

    protected String getPublishDate() {
        return publishDate;
    }

    protected int getPublishID() {
        return publishID;
    }

    protected boolean isAcceptence() {
        return acceptence;
    }


    //==============================================================================================
}
