package group14.foodfetch;

/**
 * The object of user
 * Created by s141680 on 15-3-2017.
 */

public class User {


    //a constructor:================================================================================
    public User(String email, String password, boolean is){
        setEmail(email);
        setPassword(password);
        setFoodBank(is);


        setUserID( 11111 ); //need to improve

    }
    //----------------------------------------------------------------------------------------------



    //variables:====================================================================================
    private int userID; //a unique userID will be generated by the system. set function should do this
    private String userName;  //a userName is displayed when a post is published

    //Following information is need to be filled when register by users
    private String email;
    private String password;
    private boolean isFoodBank;
    //----------------------------------------------------------------------------------------------



    //get and set functions: =======================================================================

    //set():

    public void setUserID(int userID) {
        this.userID = userID;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setFoodBank(boolean foodBank) {
        isFoodBank = foodBank;
    }

    //----------------------------------------------------------------------------------------------


    //get() :
    public int getUserID() {
        return userID;
    }

    public String getUserName() {
        return userName;
    }

    public String getEmail() {
        return email;
    }

    public String getPassword() {
        return password;
    }

    public boolean isFoodBank() {
        return isFoodBank;
    }

    //----------------------------------------------------------------------------------------------




}
